// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_y3QhN0HM79D-3CjamCq_2Z0YkZ3oXsE',
    appId: '1:422660051607:web:e201c5fee70e684c974fd2',
    messagingSenderId: '422660051607',
    projectId: 'jobspot-11d8f',
    authDomain: 'jobspot-11d8f.firebaseapp.com',
    storageBucket: 'jobspot-11d8f.appspot.com',
    measurementId: 'G-Z43X97CSSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXxzD-uFMThHOWidkmgQPDK-SK68BkL3Y',
    appId: '1:422660051607:android:456f0fee6bffb6a8974fd2',
    messagingSenderId: '422660051607',
    projectId: 'jobspot-11d8f',
    storageBucket: 'jobspot-11d8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCViGpCPcjGcuRZTghWtU8PgmdsapUw5ak',
    appId: '1:422660051607:ios:01481b207ac5145f974fd2',
    messagingSenderId: '422660051607',
    projectId: 'jobspot-11d8f',
    storageBucket: 'jobspot-11d8f.appspot.com',
    androidClientId: '422660051607-5sieaibv2ai45i5cmd0ljl3klkgd045n.apps.googleusercontent.com',
    iosClientId: '422660051607-plg9912oti2osmh17ilmfo4alib15518.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCViGpCPcjGcuRZTghWtU8PgmdsapUw5ak',
    appId: '1:422660051607:ios:1e7c75b86f5371f1974fd2',
    messagingSenderId: '422660051607',
    projectId: 'jobspot-11d8f',
    storageBucket: 'jobspot-11d8f.appspot.com',
    androidClientId: '422660051607-5sieaibv2ai45i5cmd0ljl3klkgd045n.apps.googleusercontent.com',
    iosClientId: '422660051607-hs5rj7jpt33403esph1immco71lne5qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobspot.RunnerTests',
  );
}
